name: kordi_mobile
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.7
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  go_router: ^11.0.0
  json_serializer: ^0.1.0
  json_serializable: ^6.7.1
  bloc: ^8.1.2
  get_it: ^7.6.4
  injectable: ^2.3.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  spider: ^4.2.2
  dartz: ^0.10.1
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  lint: ^2.1.2
  freezed: ^2.4.2
  json_annotation: ^4.8.1
  injectable_generator: ^2.4.0
  go_router_builder: ^2.3.3

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
