name: kordi_mobile
description: Kordi mobile.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  flutter:
    sdk: flutter


  flutter_svg: ^2.0.7
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  go_router: ^12.1.3
  json_serializable: ^6.7.1
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  hydrated_bloc: ^9.1.2
  get_it: ^7.6.4
  injectable: ^2.3.0
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flag: ^7.0.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.3.2
  dio: ^5.3.3
  json_annotation: ^4.8.1
  injectable_generator: ^2.4.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.3
  json_serializable: ^6.7.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/avatars/
    - assets/images/

flutter_intl:
  enabled: true
  output_dir: lib/gen

flutter_gen:
  integrations:
    flutter_svg: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
